---
title: "R Notebook"
output: 
  html_notebook:
    toc: TRUE
    code_folding: show
    highlight: kate
---


```{r setup}
library(ggplot2)
```

```{r}
library(openxlsx)
read.xlsx("../testdata/input.xlsx") -> df.input
df.input
```

```{r}
df.input[which(df.input == "evidence"), ] -> points
points[["position"]] <- "end"
points
```


```{r}
diameter.main_circle = max(points[["length"]]) / 5
points -> lines.starts
lines.starts[["position"]] <- "start"
lines.starts[["length"]] <- diameter.main_circle
rbind(lines.starts, points) -> lines
lines
```

```{r}
df.input[which(df.input == "layer"), ] -> layers
layers[["length.max"]] <- cumsum(layers[["length"]]) + diameter.main_circle
layers[["length.min"]] <- layers[["length.max"]] - layers[["length"]]
layers
```

```{r}
ggplot() +
  # main circle
  geom_rect(
    aes(ymin = 0, ymax = diameter.main_circle,
        xmin = 0, xmax = 360),
    fill = "white"
  ) +
  geom_hline(
    yintercept = diameter.main_circle,
    size = 1
  ) +
  # lines of evidence
  geom_line(
    data = lines,
    aes(x = angle,
        y = length,
        group = label)
  ) + 
  # points of evidence
  geom_point(
    data = points,
    aes(x = angle,
        y = length,
        fill = label),
    shape = 21,
    size = 6,
    stroke = 0.75
  ) +
  scale_fill_manual(
    values = df.input[["color"]],
    labels = df.input[["label"]]
  ) +
  # text labels of points of evidence
  geom_text(
    data = points,
    aes(x = angle,
        y = length,
        label = label),
    size = 4
  ) +
  # protective layers
  geom_rect(
    data = layers,
    aes(
      ymin = length.min,
      ymax = length.max,
      xmin = 0,
      xmax = 360,
      fill = color
      )
  ) +
  coord_polar() -> base

base +
  theme_void() +
  theme(
    legend.position = "none"
  ) +
  annotate("text", label = "Theory 1", x = 0, y = 0, size = 4)
```
